-- MySQL Script generated by MySQL Workbench
-- Thu Jun  5 14:43:06 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OnmiSens2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OnmiSens2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OnmiSens2` DEFAULT CHARACTER SET utf8 ;
USE `OnmiSens2` ;

-- -----------------------------------------------------
-- Table `OnmiSens2`.`Tabla de sensores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnmiSens2`.`Tabla de sensores` (
  `id_sensor` INT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `tipo` VARCHAR(30) NULL,
  PRIMARY KEY (`id_sensor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnmiSens2`.`Tabla de umbrales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnmiSens2`.`Tabla de umbrales` (
  `id_umbral` INT NULL AUTO_INCREMENT,
  `sensor_id` INT NULL,
  `valor_min` FLOAT NULL,
  `valor_max` FLOAT NULL,
  PRIMARY KEY (`id_umbral`),
  INDEX `sensor_id_idx` (`sensor_id` ASC) VISIBLE,
  CONSTRAINT `sensor_id`
    FOREIGN KEY (`sensor_id`)
    REFERENCES `OnmiSens2`.`Tabla de sensores` (`id_sensor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnmiSens2`.`Tabla de lecturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnmiSens2`.`Tabla de lecturas` (
  `id_lectura` INT NULL AUTO_INCREMENT,
  `sensor_id` INT NULL,
  `fecha` DATETIME NULL,
  `valor` FLOAT NULL,
  PRIMARY KEY (`id_lectura`),
  INDEX `id_sensor_idx` (`sensor_id` ASC) VISIBLE,
  CONSTRAINT `id_sensor`
    FOREIGN KEY (`sensor_id`)
    REFERENCES `OnmiSens2`.`Tabla de sensores` (`id_sensor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnmiSens2`.`Tabla de actuadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnmiSens2`.`Tabla de actuadores` (
  `id_actuador` INT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `estado_actual` ENUM('ON', 'OFF') NULL DEFAULT 'OFF',
  PRIMARY KEY (`id_actuador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OnmiSens2`.`Tabla de eventos de control`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OnmiSens2`.`Tabla de eventos de control` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `actuador_id` INT NULL,
  `fecha` DATETIME NULL,
  `accion` ENUM('ON', 'OFF') NULL,
  `nombre_usuario` VARCHAR(100) NULL,
  PRIMARY KEY (`id_evento`),
  INDEX `actuador_id_idx` (`actuador_id` ASC) VISIBLE,
  CONSTRAINT `actuador_id`
    FOREIGN KEY (`actuador_id`)
    REFERENCES `OnmiSens2`.`Tabla de actuadores` (`id_actuador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
