-- MySQL Script generated by MySQL Workbench
-- Fri May 30 17:36:49 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OmniSens
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OmniSens
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OmniSens` ;
USE `OmniSens` ;

-- -----------------------------------------------------
-- Table `OmniSens`.`dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OmniSens`.`dispositivo` (
  `id` VARCHAR(20) NOT NULL,
  `token` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OmniSens`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OmniSens`.`registro` (
  `id_registro` INT NOT NULL,
  `dispositivo_id` VARCHAR(20) NULL,
  `fecha_unix` BIGINT NULL,
  `actuador_id_actuador` INT NOT NULL,
  `dispositivo_id1` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_registro`, `actuador_id_actuador`, `dispositivo_id1`),
  INDEX `fk_registro_dispositivo1_idx` (`dispositivo_id1` ASC) VISIBLE,
  CONSTRAINT `fk_registro_dispositivo1`
    FOREIGN KEY (`dispositivo_id1`)
    REFERENCES `OmniSens`.`dispositivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OmniSens`.`sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OmniSens`.`sensor` (
  `id_sensor` INT NOT NULL AUTO_INCREMENT,
  `id_registro` INT NULL,
  `nombre` VARCHAR(20) NULL,
  `valor` FLOAT NULL,
  `registro_id_registro` INT NOT NULL,
  `registro_actuador_id_actuador` INT NOT NULL,
  PRIMARY KEY (`id_sensor`, `registro_id_registro`, `registro_actuador_id_actuador`),
  INDEX `fk_sensor_registro1_idx` (`registro_id_registro` ASC, `registro_actuador_id_actuador` ASC) VISIBLE,
  CONSTRAINT `fk_sensor_registro1`
    FOREIGN KEY (`registro_id_registro` , `registro_actuador_id_actuador`)
    REFERENCES `OmniSens`.`registro` (`id_registro` , `actuador_id_actuador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OmniSens`.`actuador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OmniSens`.`actuador` (
  `id_actuador` INT NULL AUTO_INCREMENT,
  `id_registro` INT NULL,
  `nombre` VARCHAR(20) NULL,
  `estado` VARCHAR(10) NULL,
  `registro_id_registro` INT NOT NULL,
  `registro_actuador_id_actuador` INT NOT NULL,
  `registro_dispositivo_id1` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_actuador`, `registro_id_registro`, `registro_actuador_id_actuador`, `registro_dispositivo_id1`),
  INDEX `fk_actuador_registro1_idx` (`registro_id_registro` ASC, `registro_actuador_id_actuador` ASC, `registro_dispositivo_id1` ASC) VISIBLE,
  CONSTRAINT `fk_actuador_registro1`
    FOREIGN KEY (`registro_id_registro` , `registro_actuador_id_actuador` , `registro_dispositivo_id1`)
    REFERENCES `OmniSens`.`registro` (`id_registro` , `actuador_id_actuador` , `dispositivo_id1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OmniSens`.`alarma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OmniSens`.`alarma` (
  `id_alarma` INT NULL AUTO_INCREMENT,
  `id_registro` VARCHAR(45) NULL,
  `gas` TINYINT NULL,
  `codigoAlarma` INT NULL,
  `registro_id_registro` INT NOT NULL,
  `registro_actuador_id_actuador` INT NOT NULL,
  `registro_dispositivo_id1` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_alarma`, `registro_id_registro`, `registro_actuador_id_actuador`, `registro_dispositivo_id1`),
  INDEX `fk_alarma_registro1_idx` (`registro_id_registro` ASC, `registro_actuador_id_actuador` ASC, `registro_dispositivo_id1` ASC) VISIBLE,
  CONSTRAINT `fk_alarma_registro1`
    FOREIGN KEY (`registro_id_registro` , `registro_actuador_id_actuador` , `registro_dispositivo_id1`)
    REFERENCES `OmniSens`.`registro` (`id_registro` , `actuador_id_actuador` , `dispositivo_id1`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
