-- MySQL Script generated by MySQL Workbench
-- Tue Jun  3 23:27:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OmniSens
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OmniSens
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OmniSens` ;
USE `OmniSens` ;

-- -----------------------------------------------------
-- Table `OmniSens`.`dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OmniSens`.`dispositivo` (
  `id` VARCHAR(20) NOT NULL,
  `token` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OmniSens`.`registro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OmniSens`.`registro` (
  `id_registro` INT NOT NULL,
  `dispositivo_id` VARCHAR(20) NULL,
  `fecha_unix` BIGINT NULL,
  `actuador_id_actuador` INT NOT NULL,
  PRIMARY KEY (`id_registro`, `actuador_id_actuador`),
  INDEX `dispositivo-id_idx` (`dispositivo_id` ASC) VISIBLE,
  CONSTRAINT `dispositivo-id`
    FOREIGN KEY (`dispositivo_id`)
    REFERENCES `OmniSens`.`dispositivo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OmniSens`.`sensor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OmniSens`.`sensor` (
  `id_sensor` INT NOT NULL AUTO_INCREMENT,
  `id_registro` INT NULL,
  `nombre` VARCHAR(20) NULL,
  `valor` FLOAT NULL,
  `registro_id_registro` INT NOT NULL,
  `registro_actuador_id_actuador` INT NOT NULL,
  PRIMARY KEY (`id_sensor`, `registro_id_registro`, `registro_actuador_id_actuador`),
  INDEX `registro_idx` (`id_registro` ASC) VISIBLE,
  CONSTRAINT `registro`
    FOREIGN KEY (`id_registro`)
    REFERENCES `OmniSens`.`registro` (`id_registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OmniSens`.`actuador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OmniSens`.`actuador` (
  `id_actuador` INT NULL AUTO_INCREMENT,
  `id_registro` INT NULL,
  `nombre` VARCHAR(20) NULL,
  `estado` VARCHAR(10) NULL,
  `registro_id_registro` INT NOT NULL,
  PRIMARY KEY (`id_actuador`, `registro_id_registro`),
  INDEX `registro_idx` (`id_registro` ASC) VISIBLE,
  CONSTRAINT `ik_registro`
    FOREIGN KEY (`id_registro`)
    REFERENCES `OmniSens`.`registro` (`id_registro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OmniSens`.`alarma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OmniSens`.`alarma` (
  `id_alarma` INT NULL AUTO_INCREMENT,
  `id_registro` VARCHAR(45) NULL,
  `gas` TINYINT NULL,
  `codigoAlarma` INT NULL,
  PRIMARY KEY (`id_alarma`),
  INDEX `id_registro_idx` (`id_registro` ASC) VISIBLE,
  CONSTRAINT `id_registro`
    FOREIGN KEY (`id_registro`)
    REFERENCES `OmniSens`.`registro` (`dispositivo_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
