-- MySQL Script generated by MySQL Workbench
-- Thu Jun  5 17:43:17 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema OnmiSens
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema OnmiSens
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `OnmiSens` DEFAULT CHARACTER SET utf8 ;
USE `OnmiSens` ;

-- -----------------------------------------------------
-- Table `OmniSens`.`devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OmniSens`.`devices` (
  `device_id` VARCHAR(50) NULL,
  `name` VARCHAR(100) NULL,
  `type` VARCHAR(50) NULL,
  `description` TEXT NULL,
  `  created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`device_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OmniSens`.`api_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OmniSens`.`api_users` (
  `id` INT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `api_key` VARCHAR(100) NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `api_key_UNIQUE` (`api_key` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OmniSens`.`sensor_data`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OmniSens`.`sensor_data` (
  `id` INT NULL AUTO_INCREMENT,
  ` device_id` VARCHAR(50) NULL,
  `timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  ` temperatura1` FLOAT NULL,
  ` temperatura2` FLOAT NULL,
  `humedad_relativa` FLOAT NULL,
  `presion_atm` FLOAT NULL,
  `luz` FLOAT NULL,
  ` uv` FLOAT NULL,
  ` gas_level` VARCHAR(20) NULL,
  `codigo_alarma` VARCHAR(10) NULL,
  PRIMARY KEY (`id`),
  INDEX `device_id_idx` (` device_id` ASC) VISIBLE,
  CONSTRAINT `device_id`
    FOREIGN KEY (` device_id`)
    REFERENCES `OmniSens`.`devices` (`device_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OmniSens`.`actuator_status`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OmniSens`.`actuator_status` (
  `id` INT NULL AUTO_INCREMENT,
  `device_id` VARCHAR(50) NULL,
  `timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `rele1_status` TINYINT NULL,
  `rele2_status` TINYINT NULL,
  `pwm_value` VARCHAR(45) NULL,
  `Estado de actuadorescol` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `device_id_idx` (`device_id` ASC) VISIBLE,
  CONSTRAINT `ik_device_id`
    FOREIGN KEY (`device_id`)
    REFERENCES `OmniSens`.`devices` (`device_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `OmniSens`.`commands_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `OmniSens`.`commands_log` (
  `id` INT NULL AUTO_INCREMENT,
  ` device_id` VARCHAR(50) NULL,
  ` timestamp` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `actuator` VARCHAR(50) NULL,
  `action` VARCHAR(20) NULL,
  `value` VARCHAR(50) NULL,
  PRIMARY KEY (`id`),
  INDEX `device_id_idx` (` device_id` ASC) VISIBLE,
  CONSTRAINT `uk_device_id`
    FOREIGN KEY (` device_id`)
    REFERENCES `OmniSens`.`devices` (`device_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
